config/routes.rb
Rails.application.routes.draw do
  resources :videos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'videos#index'
end

app/models/processing_metadata.rb
class ProcessingMetadata
  include Mongoid::Document

  embedded_in :video

  field :step, type: String
  field :format, type: String
  field :progress, type: Float, default: 0
end

app/models/thumbnail.rb
class Thumbnail
  include Mongoid::Document

  embedded_in :video

  # Here background uploading is not used since this entity would be created in
  # background already
  mount_uploader :file, ::ImageUploader
end

app/models/video.rb
class Video
  include Mongoid::Document
  include Mongoid::Timestamps

  # ActiveRecord has this by default.
  # Since it is Mongoid::Document
  # we might need this for data processing at background jobs
  # https://github.com/rails/activemodel-globalid
  # I allows model to be serialized / deserialized by unique identifier
  include GlobalID::Identification

  embeds_many :thumbnails

  embeds_many :processing_metadatas

  # Basic fields configuration
  field :title, type: String
  # file_tmp is used for temporary file saving while
  # it processed and stored in the background by carrierwave_backgrounder gem
  field :file_tmp, type: String
  # file_processing attribute is managed by carrierwave_backgrounder when
  # to track is file under processing or not
  field :file_processing, type: Boolean
  # Video duration would be extracted from video metadata
  field :file_duration, type: Integer
  # This would be updated during file processing to track processing progress
  # from 0 to 1
  field :progress, type: Float, default: 0
  # Config option: generate thumbnails for each video second or not
  field :needs_thumbnails, type: Boolean, default: false

  # All user applied effects is stored as array
  field :effects, type: Array, default: []

  # File ffmpeg metadata is stored at hash
  field :metadata, type: Hash, default: {}

  # mount_on is specified here because without it gem
  # would name filename attribute as file_filename
  # In some way it looks logical. But in our case it is strange to have
  # file_filename attribute at database
  mount_uploader :file, ::VideoUploader, mount_on: :file
  process_in_background :file
  store_in_background :file, ::VideoSaverWorker
  validates_presence_of :file

  # The same as above. We do not want to have watermark_image_filename attribute
  mount_uploader :watermark_image, ::ImageUploader, mount_on: :watermark_image

  validates :title, presence: true
  validate :effects_allowed_check

  # This is not good idea to let this thing update database field many times
  # It is made just to test how it works
  def processing_progress(format, format_options, new_progress)
    ProgressCalculator.new(self, format, format_options, new_progress).update!
  end

  def save_metadata(new_metadata)
    set(
      metadata: new_metadata,
      file_duration: new_metadata[:format][:duration]
    )
  end

  def save_thumbnail_files(files_list)
    files_list.each do |file_path|
      ::File.open(file_path, 'r') do |f|
        thumbnails.create!(file: f)
      end
    end
  end

  # before_transcode callback
  # Callback method accepts format and raw options but we do not need them here
  def processing_init_callback(_, _)
    clean_datas
  end

  def processing_completed_callback
    ::ActionCable.server.broadcast(
      'notifications_channel',
      ::CableData::VideoProcessing::CompletedSerializer.new(self).as_json
    )
  end

  private

  def effects_allowed_check
    effects.each do |effect|
      unless ::VideoUploader::ALLOWED_EFFECTS.include?(effect)
        errors.add(:effects, :not_allowed, effect: effect.humanize)
      end
    end
  end

  def clean_datas
    processing_metadatas.destroy_all
    thumbnails.destroy_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[show edit update destroy]

  # GET /videos
  def index
    @videos = Video.order_by(created_at: :desc).page(params[:page])
  end

  # GET /videos/1
  # def show
  # end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  # def edit
  # end

  # POST /videos
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /videos/1
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /videos/1
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def video_params
    params.require(:video).permit(:title, :file, :watermark_image, :needs_thumbnails, effects: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video Manipulator</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="light-blue lighten-1" role="navigation">
      <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Video Manipulator</a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "Videos", videos_path %></li>
        </ul>

        <ul id="nav-mobile" class="side-nav">
          <li><%= link_to "Videos", videos_path %></li>
        </ul>
        <a href="/" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>
    <div class="section no-pad-bot" id="index-banner">
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_for(video) do |f| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field">
      <%= f.text_field :title, placeholder: 'Title' %>
    </div>
  </div>

  <div class="row">
    <div class="file-field input-field">
      <div class="btn">
        <span>File</span>
        <%= f.file_field :file %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </div>

  <div class="row">
    <span>Effects</span>
    <% ::VideoUploader::ALLOWED_EFFECTS.each do |effect| %>
      <div class="input-field">
        <%= f.check_box :effects, {id: "effects_#{effect}", multiple: true, checked: f.object.effects.include?(effect) }, effect, nil %>
        <%= f.label :effects, effect.humanize, id: "effects_#{effect}", for: "effects_#{effect}" %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="file-field input-field">
      <div class="btn">
        <span>Watermark Image</span>
        <%= f.file_field :watermark_image %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="input-field">
      <%= f.check_box :needs_thumbnails, { id: "needs_thumbnails", checked: f.object.needs_thumbnails } %>
      <%= f.label :needs_thumbnails, 'Needs thumbnails', id: "needs_thumbnails", for: "needs_thumbnails" %>
    </div>
  </div>

  <div class="row">
    <button class="btn waves-effect waves-light" type="submit" name="action">
      Submit<i class="material-icons right">send</i>
    </button>
  </div>
<% end %>

app/views/videos/_info.html.erb
<div id="video_info_<%= video.id %>">
  <p id="notice"><%= notice %></p>

  <h1 class="header center orange-text">Video <%= video.id %></h1>

  <p>
    <strong>Title:</strong>
    <%= video.title %>
  </p>

  <p>
    <strong>Video File:</strong><br/>
    <%= video_tag(video.file.url, controls: true) if video.file.url.present? %>
  </p>

  <p>
    <strong>Effects:</strong>
    <%= video.effects.map { |e| e.to_s.humanize }.join(', ') %>
  </p>

  <%= render partial: 'videos/progress', locals: { video: video } %>

  <p>
    <strong>File processing:</strong>
    <%= video.file_processing? ? "Yes" : "No" %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= "#{video.file_duration} Seconds" if video.file_duration %>
  </p>

  <p>
    <strong>Needs thumbnails:</strong>
    <%= video.needs_thumbnails? ? "Yes" : "No" %>
  </p>

  <% if video.thumbnails.count.positive? %>
    <p id='thumbnails'>
      <strong>Thumbnails:</strong>
      <div class="carousel">
        <% video.thumbnails.each do |thumbnail| %>
          <div class="carousel-item">
            <%= image_tag(thumbnail.file.url) %>
          </div>
        <% end %>
      </div>
    </p>
  <% end %>

  <p>
    <strong>Metadata:</strong>
  <pre>
    <%= JSON.pretty_generate(video.metadata) unless video.metadata.empty? %>
  </pre>
  </p>

  <%= link_to 'Edit', edit_video_path(video) %> |
  <%= link_to 'Back', videos_path %>

</div>

app/views/videos/_progress.html.erb
<div id="video_progress_<%= video.id %>">
  <p>
    <strong>File processing progress:</strong>
    <div class="progress">
        <div class="determinate" style="width: <%= (video.progress.to_f * 100).round %>%"></div>
    </div>
  </p>

  <% video.processing_metadatas.each do |pm| %>
    <p>
      <strong><%= pm.step.humanize %> (<%= pm.format %>):</strong>
      <div class="progress">
          <div class="determinate" style="width: <%= (pm.progress.to_f * 100).round %>%"></div>
      </div>
    </p>
  <% end %>
</div>

app/views/videos/edit.html.erb
<h1 class="header center orange-text">Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="header center orange-text">Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>File</th>
      <th>Progress</th>
      <th>Processing</th>
      <th>Duration, Sec</th>
      <th>Created At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= image_tag(video.file.url(:thumb), width: "200") if video.file.url(:thumb).present? %></td>
        <td><%= (video.progress.to_f * 100).round %>%</td>
        <td><%= video.file_processing? ? "Yes" : "No" %></td>
        <td><%= video.file_duration %></td>
        <td><%= video.created_at %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @videos %>

<br>

<%= link_to 'New Video', new_video_path, class: "waves-effect waves-light btn" %>

app/views/videos/new.html.erb
<h1 class="header center orange-text">New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<%= render partial: 'videos/info', locals: { video: @video } %>

<% if @video.thumbnails.count.positive? %>
  <script>
     $(document).ready(function () {
         $('.carousel').carousel({});
     });
  </script>
<% end %>